#pragma checksum "..\..\..\..\Core\UserPages\LookUp.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "44E08E7CADDCD5BBDF445AB5501257D6439C94170FA4583A18FDF4259ED6FAB6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Finance_App_V2.Core.UserPages;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Finance_App_V2.Core.UserPages {
    
    
    /// <summary>
    /// LookUp
    /// </summary>
    public partial class LookUp : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 39 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox search;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Ticker;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label CurrentPrice;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label CEO;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Employees;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Headquarters;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Founded;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Marketcap;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label PriceEarningsratio;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Dividendyield;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Averagevolume;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Hightoday;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Lowtoday;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Openprice;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Volume;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Yearhigh;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\Core\UserPages\LookUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Yearlow;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Finance App V2;component/core/userpages/lookup.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Core\UserPages\LookUp.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.search = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            
            #line 40 "..\..\..\..\Core\UserPages\LookUp.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Search);
            
            #line default
            #line hidden
            return;
            case 3:
            this.Ticker = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.CurrentPrice = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.CEO = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.Employees = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.Headquarters = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.Founded = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.Marketcap = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.PriceEarningsratio = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.Dividendyield = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.Averagevolume = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.Hightoday = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.Lowtoday = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.Openprice = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.Volume = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.Yearhigh = ((System.Windows.Controls.Label)(target));
            return;
            case 18:
            this.Yearlow = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

